# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'LTxMsg' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LTxMsg
  pod 'LTxCore',:git=>"https://github.com/liangtongdev/LTxCore.git"
  pod 'LTxMsg', :path => '../'

end
